import yaml
import random

GRID_SIZE = 6
SUBNET_BASE = "172.20"

# Balanced Key Spawning Logic
# Home Bases: Red (0,0), Blue (5,5)
# Neutral Zone: 2,2 to 3,3 (Central 4 nodes)
def get_balanced_key():
    while True:
        x = random.randint(2, 3)
        y = random.randint(2, 3)
        # Verify distance balance
        dist_red = x + y
        dist_blue = (GRID_SIZE-1 - x) + (GRID_SIZE-1 - y)
        if abs(dist_red - dist_blue) <= 1:
            return x, y

key_x, key_y = get_balanced_key()
key_coords = f"{key_x},{key_y}"
print(f"THE KEY IS AT: {key_x}, {key_y} (Balanced)")

compose = {
    "version": "3.8",
    "services": {},
    "networks": {
        "arena_net": {
            "driver": "bridge",
            "ipam": {
                "config": [
                    {"subnet": f"{SUBNET_BASE}.0.0/16"}
                ]
            }
        }
    }
}

# Generate 16 Nodes
for y in range(GRID_SIZE):
    for x in range(GRID_SIZE):
        service_name = f"node_{y}_{x}"
        container_name = f"arena_{y}_{x}"
        ip_addr = f"{SUBNET_BASE}.{y}.{10+x}"
        
        has_key = "false"
        if x == key_x and y == key_y:
            has_key = "true"
        
        compose["services"][service_name] = {
            "build": {
                "context": ".",
                "dockerfile": "Dockerfile.node"
            },
            "container_name": container_name,
            "networks": {
                "arena_net": {
                    "ipv4_address": ip_addr
                }
            },
            "environment": [
                f"HAS_KEY={has_key}",
                f"GRID_SIZE={GRID_SIZE}",
                f"COORDINATE_KEY={y},{x}"
            ],
            "cap_add": ["NET_ADMIN"],
            "restart": "unless-stopped",
            "deploy": {
                "resources": {
                    "limits": {
                        "cpus": "0.50",
                        "memory": "256M"
                    }
                }
            }
        }

# Add Orchestrator
compose["services"]["orchestrator"] = {
    "build": {
        "context": "./orchestrator",
        "dockerfile": "Dockerfile"
    },
    "container_name": "arena_orchestrator",
    "environment": [
        f"KEY_LOCATION={key_coords}",
        f"GRID_SIZE={GRID_SIZE}"
    ],
    "volumes": [
        "/var/run/docker.sock:/var/run/docker.sock"
    ],
    "ports": ["5000:5000"],
    "networks": ["arena_net"]
}

with open("docker-compose.yml", "w") as f:
    f.write("# GENERATED BY generate_grid.py\n")
    yaml.dump(compose, f, sort_keys=False)

print(f"Generated docker-compose.yml w/ KEY at {key_coords}")
