import yaml

GRID_SIZE = 4
SUBNET_BASE = "172.20"

compose = {
    "version": "3.8",
    "services": {},
    "networks": {
        "arena_net": {
            "driver": "bridge",
            "ipam": {
                "config": [
                    {"subnet": f"{SUBNET_BASE}.0.0/16"}
                ]
            }
        }
    }
}

# Generate 64 Nodes
for y in range(GRID_SIZE):
    for x in range(GRID_SIZE):
        service_name = f"node_{y}_{x}"
        container_name = f"arena_{y}_{x}"
        # Calculate IP: 172.20.0.10 + index
        # To avoid overflow 0-255 in last octet, we might need to use third octet for rows?
        # Let's simple mapping: 172.20.{y}.{10+x}
        ip_addr = f"{SUBNET_BASE}.{y}.{10+x}"
        
        compose["services"][service_name] = {
            "build": {
                "context": ".",
                "dockerfile": "Dockerfile.node"
            },
            "container_name": container_name,
            "networks": {
                "arena_net": {
                    "ipv4_address": ip_addr
                }
            },
            "cap_add": ["NET_ADMIN"],
            "restart": "unless-stopped",
            "deploy": {
                "resources": {
                    "limits": {
                        "cpus": "0.50",
                        "memory": "256M"
                    }
                }
            }
        }

# Add Orchestrator
compose["services"]["orchestrator"] = {
    "build": {
        "context": "./orchestrator",
        "dockerfile": "Dockerfile"
    },
    "container_name": "arena_orchestrator",
    "volumes": [
        "/var/run/docker.sock:/var/run/docker.sock"
    ],
    "ports": ["5000:5000"],
    "networks": ["arena_net"]
}

with open("docker-compose.yml", "w") as f:
    f.write("# GENERATED BY generate_grid.py\n")
    yaml.dump(compose, f, sort_keys=False)

print("Generated docker-compose.yml for 8x8 grid.")
