import yaml
import random

GRID_SIZE = 4
SUBNET_BASE = "172.20"

# Pick a random node for the Key (Flag)
# Avoid 0,0 (Start) to make it hard
key_x = random.randint(1, GRID_SIZE-1)
key_y = random.randint(1, GRID_SIZE-1)
key_coords = f"{key_x},{key_y}"
print(f"THE KEY IS AT: {key_x}, {key_y}")

compose = {
    "version": "3.8",
    "services": {},
    "networks": {
        "arena_net": {
            "driver": "bridge",
            "ipam": {
                "config": [
                    {"subnet": f"{SUBNET_BASE}.0.0/16"}
                ]
            }
        }
    }
}

# Generate 16 Nodes
for y in range(GRID_SIZE):
    for x in range(GRID_SIZE):
        service_name = f"node_{y}_{x}"
        container_name = f"arena_{y}_{x}"
        ip_addr = f"{SUBNET_BASE}.{y}.{10+x}"
        
        has_key = "false"
        if x == key_x and y == key_y:
            has_key = "true"
        
        compose["services"][service_name] = {
            "build": {
                "context": ".",
                "dockerfile": "Dockerfile.node"
            },
            "container_name": container_name,
            "networks": {
                "arena_net": {
                    "ipv4_address": ip_addr
                }
            },
            "environment": [
                f"HAS_KEY={has_key}"
            ],
            "cap_add": ["NET_ADMIN"],
            "restart": "unless-stopped",
            "deploy": {
                "resources": {
                    "limits": {
                        "cpus": "0.50",
                        "memory": "256M"
                    }
                }
            }
        }

# Add Orchestrator
compose["services"]["orchestrator"] = {
    "build": {
        "context": "./orchestrator",
        "dockerfile": "Dockerfile"
    },
    "container_name": "arena_orchestrator",
    "environment": [
        f"KEY_LOCATION={key_coords}"
    ],
    "volumes": [
        "/var/run/docker.sock:/var/run/docker.sock"
    ],
    "ports": ["5000:5000"],
    "networks": ["arena_net"]
}

with open("docker-compose.yml", "w") as f:
    f.write("# GENERATED BY generate_grid.py\n")
    yaml.dump(compose, f, sort_keys=False)

print(f"Generated docker-compose.yml w/ KEY at {key_coords}")
